# Generated by Django 6.1 on 2026-08-25 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pecasDeComputador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processador', models.CharField(blank=True, max_length=100)),
                ('placaMae', models.CharField(blank=True, max_length=100)),
                ('memoriaRam', models.CharField(blank=True, max_length=100)),
                ('armazenamento', models.CharField(blank=True, max_length=100)),
                ('placaDeVideo', models.CharField(blank=True, max_length=100)),
                ('fonte', models.CharField(blank=True, max_length=100)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computador.computador')),
            ],
        ),
    ]
