# Generated by Django 6.1.1 on 2026-10-02 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computador', '0002_computador_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecasdecomputador',
            name='computador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='computador.computador'),
        ),
    ]
