# Generated by Django 6.1.1 on 2026-10-02 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computador', '0003_alter_pecasdecomputador_computador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armazenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armazenamento', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoriaRam', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlacaDeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placaDeVideo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlacaMae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placaMae', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Processador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processador', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pecasdecomputador',
            name='computador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='computador.computador'),
        ),
        migrations.AlterField(
            model_name='pecasdecomputador',
            name='armazenamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='computador.armazenamento'),
        ),
        migrations.AlterField(
            model_name='pecasdecomputador',
            name='fonte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='computador.fonte'),
        ),
        migrations.AlterField(
            model_name='pecasdecomputador',
            name='memoriaRam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='computador.memoriaram'),
        ),
        migrations.AlterField(
            model_name='pecasdecomputador',
            name='placaDeVideo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='computador.placadevideo'),
        ),
        migrations.AlterField(
            model_name='pecasdecomputador',
            name='placaMae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='computador.placamae'),
        ),
        migrations.AlterField(
            model_name='pecasdecomputador',
            name='processador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='computador.processador'),
        ),
    ]
