# Generated by Django 6.1.1 on 2026-10-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computador', '0004_armazenamento_fonte_memoriaram_placadevideo_placamae_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placamae',
            name='chipset',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='placamae',
            name='socket',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='placamae',
            name='tipo_memoria',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
